apiVersion: batch/v1
kind: Job
metadata:
  name: image-puller-job
  namespace: argo
spec:
  template:
    metadata:
      labels:
        app: image-puller-job
    spec:
      nodeSelector:
        argo: enable
      imagePullSecrets:
        - name: default-secret  # 指定 imagePullSecret 的名称
      containers:
      - name: image-puller
        image: swr.ap-southeast-3.myhuaweicloud.com/powercloud/dp_xac_service:24.4.400_20241210162714
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          sleep 10000000
      restartPolicy: OnFailure
