apiVersion: batch/v1
kind: Job
metadata:
  name: debug-template
  namespace: argo
spec:
  entrypoint: debug-template
  imagePullSecrets:
    - name: default-secret
  templates:
    - name: debug-template
      metadata:
        annotations:
          sidecar.istio.io/inject: 'false'
      container:
        image: swr.ap-southeast-3.myhuaweicloud.com/powercloud/dp_xac_service:24.4.400_20241210162714
        command: ["/bin/sh", "-c"]
        args:
        - |
          sleep 10000000
      nodeSelector:
        argo: enable
      restartPolicy: OnFailure
